/*
 * This file is generated by jOOQ.
 */
package io.jacobking.jooq;


import io.jacobking.jooq.tables.Security;
import io.jacobking.jooq.tables.records.SecurityRecord;

import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables in the
 * default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<SecurityRecord> SECURITY__PK_SECURITY = Internal.createUniqueKey(Security.SECURITY, DSL.name("pk_SECURITY"), new TableField[] { Security.SECURITY.USERNAME }, true);
}
