/*
 * This file is generated by jOOQ.
 */
package io.jacobking.jooq;


import io.jacobking.jooq.tables.Security;


/**
 * Convenience access to all tables in the default schema.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>SECURITY</code>.
     */
    public static final Security SECURITY = Security.SECURITY;
}
